### ISSUE TITLE
To be Explicit or Implicit?

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/x509-slhdsa#16]
Settle on whether ASN.1 module should be implicit or explicit.

**Comment by danvangeest** [comment]
By sheer force of numbers, it'll be IMPLICIT.

**Comment by seanturner** [comment]
You can go ahead and close this one out based on [this](https://mailarchive.ietf.org/arch/msg/spasm/-zua7zlQ-0QBUcyQta3EKgqp7u0/).
