### ISSUE TITLE
Hash-SLH-DSA OIDs

### ISSUE THREAD

**Issue by danvangeest** [lamps-wg/x509-slhdsa#9]
Once NIST publishes FIPS205, decide what to do about pure vs predigest mode.  If we only support pure mode, add this text to the introduction:

> The final version of {{FIPS205}} is expected to define two signature modes: pure mode and predigest mode.  This document only specifies the use of pure mode with X.509 certificates and CRLs.

**Comment by fluppe2** [comment]
NIST assigned OIDs to the parameter sets of the "pure" version of SLH-DSA and specific "pre-hash" combinations. See https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration

Would it be better to include the "pre-hash" versions that have OIDs assigned for the sake of completeness?

**Comment by danvangeest** [comment]
While the WG determined that they do not want HashML-DSA because ML-DSA can have the message representative calculated by a different module (outside an HSM for example), this is not possible for SLH-DSA because it does a dual-pass.  The WG still thinks that HashSLH-DSA is not necessary for use by CA certificates, but we can't control what will be done by EE users, so during the presentation I said that we will add a section specifying HashSLH-DSA OIDs for use in SPKI of end-entity certificates.

There is also a desire to prune the OIDs, but I think we should just offer all them all first and then if people complain hard and offer suggestions, reduce the list.
